### ISSUE TITLE
add ability to click on error panel entry and move the cursor to the particular error location

### ISSUE THREAD

**Issue by MiguelCastillo** [MiguelCastillo/Brackets-InteractiveLinter#116]

**Comment by MiguelCastillo** [comment]
Not applicable. it is already supported... :)

**Comment by MiguelCastillo** [comment]
The error was a regression in JSX support

**Comment by MiguelCastillo** [comment]
Its actually not fully implemented.  we take the cursor to the line number but not the column where the issue happens.

**Comment by Mark-Simulacrum** [comment]
It seems that the lint panel should be sending the user to the correct character position: https://github.com/MiguelCastillo/Brackets-InteractiveLinter/blob/master/lintPanel.js#L74.

Not sure why the character field isn't being set/isn't set correctly.

**Comment by MiguelCastillo** [comment]
@Mark-Simulacrum yeah you are right!  Thanks for pointing that out.

**Comment by MiguelCastillo** [comment]
fixed https://github.com/MiguelCastillo/Brackets-InteractiveLinter/pull/118
