### ISSUE TITLE
.jshintrc configuration not loaded

### ISSUE THREAD

**Issue by rtp-calpoly** [MiguelCastillo/Brackets-InteractiveLinter#119]
I am trying to use a .jshintrc configuration file within the root of my project, but I cannot make InteractiveLint to load those settings. I have attached a screenshot in which I show the .jshintrc configuration file and my JavaScript file. The configuration file for my brackets project is (I am showing only linting-related options):

    {
        "linting.collapsed": false,
        "language": {
            "javascript": {
                "linting.prefer": [
                    "jshint"
                ],
                "linting.usePreferredOnly": true
            }
        },
        "interactive-linter.javascript": [
            "jshint"
        ]
    }

The configuration file for the JSHint plugin within the InteractiveLinter is the following:

    {
        "language": "javascript",
        "settingsFile": ".jshintrc"
    }

I have followed the recommendations from issues #2 and #22 , but I have obtained no progress. What can I be doing wrong?

![screenshot from 2015-04-03 10 28 31](https://cloud.githubusercontent.com/assets/5666358/6985817/13bbe3b4-d9ec-11e4-89a2-5d50d83c94f9.png)

**Comment by MiguelCastillo** [comment]
@rtp-calpoly quick question.  Did you restart Brackets after you created the jshintrc file? or was the jshintrc file before and you started Brackets?

There is an issue with interactive linter where newly created jshintrc files are not picked up until Brackets is restarted.  I wonder if that's what's happening.

**Comment by rtp-calpoly** [comment]
@MiguelCastillo I restarted Brackets after creating the .jshintrc file by myself. Should I better remove that file, restart Brackets and wait for InteractiveLint to create its own?

**Comment by MiguelCastillo** [comment]
@rtp-calpoly no need to delete the file.  I am still puzzled by this.  With brackets loaded, could you open up brackets' dev tools and see if there are any errors from interactive linter?

**Comment by rtp-calpoly** [comment]
@MiguelCastillo : I have just arrived home and I am trying it with a "fresh" brackets installation. I had an initial .jshintrc file and I installed InteractiveLint, reloaded brackets and, as far as I understand, it should have automatically loaded the settings from the .jshintrc file and applied them to the project, am I wrong?

I also removed the .jshintrc file and restarted brackets twice for InteractiveLint to create the initial .jshintrc at the root of the project, although I am not so sure that this is the behavior that I should expect from your plugin.

Any help is more than appreciated.

**Comment by MiguelCastillo** [comment]
@rtp-calpoly yeah interactive linter will automatically pick up any `.jshintrc` file in your project.  Did you get a chance to check the console log in the dev tools?

**Comment by MiguelCastillo** [comment]
@rtp-calpoly I just reinstalled interactive linter, and setup a `.jshintrc` file and it works like a champ...  let's see if the console log shows any problems.

**Comment by MiguelCastillo** [comment]
@rtp-calpoly have you had a chance to check with the devtools console?

**Comment by rtp-calpoly** [comment]
@MiguelCastillo , check this out:

    NodeSocketTransport - start /LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:87
    Worker: No parameter type found ScopeManager.js:1072
    Worker: No parameter type found ScopeManager.js:1072
    Worker: No parameter type found ScopeManager.js:1072
    Worker: Error thrown in tern_worker:Cannot read property 'length' of undefined
    TypeError: Cannot read property 'length' of undefined
        at processInferFnTypeParameters (file:///opt/brackets/www/extensions/default/JavaScriptCodeHints/tern-worker.js:459:51)
        at getParameters (file:///opt/brackets/www/extensions/default/JavaScriptCodeHints/tern-worker.js:481:24)
        at file:///opt/brackets/www/extensions/default/JavaScriptCodeHints/tern-worker.js:525:42
        at file:///opt/brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/tern.js:139:9
        at run (file:///opt/brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/tern.js:209:9)
        at Object.exports.withTimeout (file:///opt/brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:674:18)
        at file:///opt/brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/tern.js:211:65
        at Object.exports.withContext (file:///opt/brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:657:18)
        at file:///opt/brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/tern.js:211:13
        at analyzeAll (file:///opt/brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/tern.js:331:15)     ScopeManager.js:1072
    Worker: No parameter type found ScopeManager.js:1072
    Worker: No parameter type found 

... appears in the "Logs" tab, but not either as an exception or as an error; that is the reason why I did not find it yesterday... what is the problem about?

**Comment by MiguelCastillo** [comment]
@rtp-calpoly that's the javascript code hinting functionality in Brackets having some issues.  I don't believe that's related to interactive linter.

But one thing is that jshint is the default linter in interactive linter.  Have you tried just removing the interactive-linter configuration from `.brackets.json`?   Do you have anything defined in the global `brackets.json`?

**Comment by rtp-calpoly** [comment]
@MiguelCastillo , right now, I only have the global configuration file for Brackets, that contains the following configuration:

    {
        "jwolfe.file-tree-exclude.list": [
            "node_modules",
            "bower_components",
            ".git",
            "dist",
            "vendor"
        ]
    }

I do not think that this configuration is lint-related. I might have to re-install brackets and be really careful with its configuration. I cannot understand what I could have done wrong.

**Comment by MiguelCastillo** [comment]
@rtp-calpoly i dont see anything wrong with that... I dont think it is necessary to reinstall brackets.

**Comment by MiguelCastillo** [comment]
@rtp-calpoly i am just noticing that you are running in Ubuntu, or some other similar distro of Linux.  I am not sure if that has anything to do with this.  I will run a couple tests there and see what happens.  Also, what version of Brackets do you have installed?

**Comment by rtp-calpoly** [comment]
@MiguelCastillo , I would swear that I am using the last available one:

    Release 1.2 experimental build 1.2.0-15697 (release 8f82e2a97) 
    build timestamp: Tue Feb 24 2015 21:16:20 GMT-0800

... I have just realized that it is an "experimental" one - I was not aware of this. Might I check with people at Brackets better?

**Comment by MiguelCastillo** [comment]
@rtp-calpoly nope that version look good.

**Comment by rtp-calpoly** [comment]
@MiguelCastillo , ok, I tried the following:

1) I removed Brackets and all its related folders ($HOME/.config/Brackets and /opt/brackets).
2) I installed Brackets from scratch with no extensions.
3) I configured only "FileTreeExclude" and "JSHint".
4) "JSHint" was configured with its own ".jshintrc" file at the root of the project. It works well and adds "angular" as a predefined global word (see the first screenshot).
5) Once I got "JSHint" working, I installed "InteractiveLinter" and without restarting Brackets, it does not read the ".jshintrc" (see the second screenshot).
6) I tried to restart Brackets but I cannot close the window, I have to kill the process from within the console.
7) I open the DevTools just to check what is going on before killing Brackets within the console, and I found an error (see the third screenshot).
8) I kill Brackets within the console and I start it again. The problem with closing Brackets dissapears, but InteractiveLinter is not reading .jshintrc file.

Any ideas? Thank you so much in advance for your patience!

![screenshot from 2015-04-04 11 39 06](https://cloud.githubusercontent.com/assets/5666358/6994050/3ca32458-dabf-11e4-81a5-8896e19b44f2.png)
![screenshot from 2015-04-04 11 39 43](https://cloud.githubusercontent.com/assets/5666358/6994052/3ca9b174-dabf-11e4-8415-fcc2155783a9.png)
![screenshot from 2015-04-04 11 40 21](https://cloud.githubusercontent.com/assets/5666358/6994051/3ca93a50-dabf-11e4-88f6-ed28f969fb2f.png)

**Comment by rtp-calpoly** [comment]
@MiguelCastillo , in my case it is working now with the new "cloned" version... awesome job! You should get a badget for "best customer support" :+1: 

![screenshot from 2015-04-05 10 44 31](https://cloud.githubusercontent.com/assets/5666358/6997816/f2bc7b34-db7f-11e4-97a9-0396d75437e8.png)
