### ISSUE TITLE
Linter settings are not reliably loaded on all platforms

### ISSUE THREAD

**Issue by Mark-Simulacrum** [MiguelCastillo/Brackets-InteractiveLinter#122]
As detailed in #120 and #119, on Ubuntu -- and perhaps other operating systems -- We need to call `FileUtils.getDirectoryPath` and `stripTrailingSlashes` on files in order to allow the file path of the settings to be correctly found/loaded.

If working up the file tree (traversing) works, then perhaps the issue happens due to a trailing slash being present in the path. In that case, we can a) simply call `stripTrailingSlashes` on the file path, and more accurately, find out the source of the trailing slash and remove it there.

**Comment by MiguelCastillo** [comment]
fixed with https://github.com/MiguelCastillo/Brackets-InteractiveLinter/pull/121
