### ISSUE TITLE
Interactive linter and HTML: "no start tag"

### ISSUE THREAD

**Issue by rtp-calpoly** [MiguelCastillo/Brackets-InteractiveLinter#127]
I am posting this issue despite that I am aware that it might not be an issue directly attributable to the Interactive Linter plugin. When examining the following piece of HTML code:

    <form name="tle-select" ng-controller="tleSelectCtrl">
        <input type="radio" ng-model="i.tle_select" value="manual">manual</input>
        <input type="radio" ng-model="i.tle_select" value="auto">auto</input>
    </form>

... Interactive Linter returns the following two errors (one per line) as a result of the inspection:

    Tag must be paired, No start tag: [ </input> ]	 <input type="radio" ng-model="i.tle_select" value="manual">manual</input>
    Tag must be paired, No start tag: [ </input> ]	 <input type="radio" ng-model="i.tle_select" value="auto">auto</input>

I have also attached a screenshot of Brackets Release 1.3 experimental build 1.3.0-16022, under Debian 8 "Jessie".

Any ideas?

![screenshot from 2015-04-27 16 13 16](https://cloud.githubusercontent.com/assets/5666358/7359839/6a020982-ecf8-11e4-8d91-f54e7d59a136.png)

**Comment by andrewnaumann** [comment]
hey @rtp-calpoly ! I was looking over your code and I think the issue is that input is a void element. You shouldn't be closing it.  This is from W3.org

>A void element is an element whose content model never allows it to have contents under any circumstances. Void elements can have attributes.

>The following is a complete list of the void elements in HTML:

>area, base, br, col, command, embed, hr, img, input, keygen, link, meta, param, source, track, wbr

You can find what I quoted in section 4.3
http://www.w3.org/TR/html-markup/syntax.html

**Comment by rtp-calpoly** [comment]
@andrewnaumann : yes, you are right. I did not know that the HTML specification permitted that kind of "relaxation" over the XHTML specification. I have changed my code to a self-closing input tag linked to a label:

    <form name="tle-select" ng-controller="tleSelectCtrl">
        <input id="manual-radio" type="radio" ng-model="i.tle_select" value="manual" />
        <label for="manual-radio">manual</label>
    </form>

Now it is working perfectly. Thanks for the help.
