### ISSUE TITLE
Can Other Linters Be Easily Added?

### ISSUE THREAD

**Issue by bobrocke** [MiguelCastillo/Brackets-InteractiveLinter#138]
Or are there plans to add YAML, SCSS, LESS, CSON and PHP linters?

**Comment by MiguelCastillo** [comment]
Other linters can be easily added.  I am really happy to take in PRs if you want to give it a try :).   I don't really have much bandwidth right now to that myself.

Here is some documentation for creating your own interactive plugins. https://github.com/MiguelCastillo/Brackets-InteractiveLinter/tree/master/plugins

**Comment by MiguelCastillo** [comment]
closing this one... if there are other questions, we can reopen or open a new issue.
