### ISSUE TITLE
eslint deprecation warnings appearing on the first line of all Javascript files

### ISSUE THREAD

**Issue by tmcdonnell87** [MiguelCastillo/Brackets-InteractiveLinter#151]
I'm getting deprecation warnings from eslint on all files. The warnings appear on the first line. They can be disabled by turning off warnings on that line or by disabling those specific warnings for the file, but it seems like they shouldn't be appearing. 

![image](https://cloud.githubusercontent.com/assets/4717014/9001366/24b97b32-370b-11e5-92b7-32c9ae868607.png)

I'm new to Brackets extensions - let me know what additional information you need to help troubleshoot. 

Thanks!

**Comment by MiguelCastillo** [comment]
@tmcdonnell87 Hi, sorry for this delayed response.  Those warnings about old settings eslint has changed.  I have the default settings file so that you dont see those again.

**Comment by tmcdonnell87** [comment]
Awesome, thanks.

**Comment by MiguelCastillo** [comment]
I meant to say that I have *updated* the default settings file so that you don't see those errors again :)
