### ISSUE TITLE
Single quotes for HTML attributes marked as error

### ISSUE THREAD

**Issue by tabweg** [MiguelCastillo/Brackets-InteractiveLinter#164]
HTML5 specification says that it can be single and double quotes or even no quotes at all if the attribute value has no white space etc.

**Comment by PhiLhoSoft** [comment]
InteractiveLinter is just a wrapper around existing tools, so you have to refer to each one to adjust their rules.
For HTML, it uses http://htmlhint.com/ so you need to look for the rule(s) about quotes.
Note it is recommended to use quotes consistently (always single or double, none isn't always possible), but if you like to mix them, I suppose you can deactivate the rule.

**Comment by MiguelCastillo** [comment]
@PhiLhoSoft yes, thank you for answering!  That is really helpful information.  You can only enforce double quotes via `attr-value-double-quotes`.  If you set the flag to false, then you are just disabling the entire quotes rule.

**Comment by MiguelCastillo** [comment]
I am closing this issue as we are working as designed...  Feel free to open other issues or continue discussions around this topic in this issue :)
