### ISSUE TITLE
Skip errors

### ISSUE THREAD

**Issue by laedri** [MiguelCastillo/Brackets-InteractiveLinter#168]
I have Chrome extension, and I use it jQuery in that extension.

Linter gives me error about `chrome.tabs.executeScript({ // foo });` (chrome not defined) and `$('foo')` ($ not defined). I don't want to see these errors.  How can I skip them?

**Comment by MiguelCastillo** [comment]
Which linter are you using?  It seems like you just need to specify an entry in your config file to tell whichever linter you are using that `chrome` and `$` are known variables.

**Comment by laedri** [comment]
JSHint. I didn't know that I can define known variables. Thanks.

**Comment by MiguelCastillo** [comment]
Awesome. Glad it works.
