### ISSUE TITLE
Support options in the header for jslint

### ISSUE THREAD

**Issue by atishay811** [MiguelCastillo/Brackets-InteractiveLinter#170]
JSLint support linter options per file via `/*jshint unused: true, node: true */` The interactive linter should support those.

**Comment by MiguelCastillo** [comment]
@atishay811  that use case is supposed to work. I am assuming **you tested it and it didn't work**, so I will double check that.

**Comment by atishay811** [comment]
It was using jshint by default. Didn't read my jslint settings. Sorry for the confusion. After I set this to jslint, everything works.

**Comment by MiguelCastillo** [comment]
Oh great! Glad it still works. Got me concerned for a moment :)
