### ISSUE TITLE
JSX plugin

### ISSUE THREAD

**Issue by DaddyWarbucks** [MiguelCastillo/Brackets-InteractiveLinter#190]
I believe I have JSX linting setup properly, but am not seeing any errors in .jsx files. I have included the  `"interactive-linter.javascript": ["jsx"]` in my `brackets.json` file. 

I can confirm that it is working in .js file extensions as expected (with ["jsx"] as set above). But I get no errors in a .jsx file, even for something like a missing semicolon

I have tried "Reload with extensions" and some other things.
I am running v1.0.5 running on the latest Brackets version on Mac.

Thanks for any help!

**Comment by CowTail** [comment]
Same.
