### ISSUE TITLE
Details links in javascript are broken - http://jslinterrors.com/ is down

### ISSUE THREAD

**Issue by albertportnoy** [MiguelCastillo/Brackets-InteractiveLinter#194]
I'm not sure if this happens for languages other than javascript, but the 'Details' link, which opens [jslinterrors.com](http://jslinterrors.com) is broken. It shows this: 
![shot-20170609-12379-tidasq](https://user-images.githubusercontent.com/14863373/26979104-52e9a540-4cf3-11e7-9f8c-7cbfbf5ba68d.png).

**Comment by MiguelCastillo** [comment]
oh no! - it seems like the site is just permanently down... https://github.com/AtomLinter/linter-jshint/issues/341

i am super busy right now... if you have a moment to figure out if its available somewhere else, that would be super cool!

**Comment by MiguelCastillo** [comment]
fixed by https://github.com/MiguelCastillo/Brackets-InteractiveLinter/pull/196
