### ISSUE TITLE
http://jslinterrors.com/  is down

### ISSUE THREAD

**Issue by anandisrocking007** [MiguelCastillo/Brackets-InteractiveLinter#195]
Hi i would like to bring to your attention that http://jslinterrors.com/  is down whenever it ask to click the link given in the error to know more it redirects to an empty site.

**Comment by MiguelCastillo** [comment]
thank you!  someone else already logged it.  https://github.com/MiguelCastillo/Brackets-InteractiveLinter/issues/194

I asked if there was any interest in finding out what has replaced that website and I will happily take a PR. 

I am going to close this issue and keep track of it under the other one.
