### ISSUE TITLE
Add support for eslint

### ISSUE THREAD

**Issue by IjzerenHein** [MiguelCastillo/Brackets-InteractiveLinter#31]
I'd love to see support for eslint and .eslintrc as well :)
Cheers, Hein

**Comment by JeffryBooher** [comment]
:+1:

**Comment by briandipalma** [comment]
I found https://github.com/peol/brackets-eslint but it is using an old version of ESLint. When I get some time I might fork it and simplify it.

**Comment by peteruithoven** [comment]
I tried using [brackets-eslint](https://github.com/peol/brackets-eslint) with the interactive linter, but it doesn't work. It's warnings don't show up. I also reported this with brackets-eslint: https://github.com/peol/brackets-eslint/issues/7

**Comment by MiguelCastillo** [comment]
Alright folks, thanks for patiently waiting. I am going to be looking into this feature this weekend.  We'll see how it goes :)

**Comment by yahyaKacem** [comment]
what's the state of this issue is it implemented yet?

**Comment by MiguelCastillo** [comment]
@yahyaKacem I am currently working on adding multiple lint support, in which I am support for preferences so that you can pick eslint.  It is coming along very well, but it is a major change so it is a bit slower than I'd like.  But please stay tuned... I will be releasing this soon

**Comment by peteruithoven** [comment]
Nice! Keep up the great work!

**Comment by yahyaKacem** [comment]
@MiguelCastillo when you said `multiple lint support` do you mean multiple JavaScript lint support or other languages too like HTMLLint and CSSLint...?
And thanks, this is better then the regular Brackets linter where I have to open it to see the errors.

**Comment by MiguelCastillo** [comment]
@yahyaKacem I have tabled multiple linter support to get eslint support quicker in your guys' hands...  But multiple linter will allow users to specify multiple linters to run in sequence.  This is very useful to allowing users to specify `jsx` and then `jshint` linting.  The purpose to have linters transform text and aggregate linting results for a more flexible linting workflow.

Anyways...  I have put up a branch with eslint support.  I need some help testing it and fine tuning, if you guys don't mind. https://github.com/MiguelCastillo/Brackets-InteractiveLinter/pull/108.  Do you guys mind giving me  a hand testing it, please?

**Comment by MiguelCastillo** [comment]
/@all alright I just merged it to master.  Please let me know if there are issue.

@yahyaKacem I am thinking about adding support for linters for other languages like CSSLint and HTMLLint.  I also would love to get PRs for those :)
