### ISSUE TITLE
Support long lines

### ISSUE THREAD

**Issue by digiguru** [MiguelCastillo/Brackets-InteractiveLinter#34]
This plugin is great, but I seem to be able to make it stop working..by having a long string concatination.

Look at this example:

``` javascript
var bar = "hello";
return "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eget elit euismod, porttitor neque vitae, scelerisque dui. Sed luctus lorem at mollis euismod. Praesent mi lectus, vulputate eget sodales sed, viverra id enim. Quisque no" + bar;
```
This throws an error - 'Bar' is defined ut never used. W098

However if you remove 1 character from the string
 
``` javascript
var bar = "hello";
return "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eget elit euismod, porttitor neque vitae, scelerisque dui. Sed luctus lorem at mollis euismod. Praesent mi lectus, vulputate eget sodales sed, viverra id enim. Quisque n" + bar;
```

It works.

(250 chracter limit)

**Comment by MiguelCastillo** [comment]
https://github.com/MiguelCastillo/Brackets-InteractiveLinter/issues/34

**Comment by MiguelCastillo** [comment]
added better detection of minified javascript.  The linter should be able to handle your sample code correctly. please let me know if you run into other issues.
