### ISSUE TITLE
RESEARCH: Use CodeInspection methods to get errors, not custom implementation

### ISSUE THREAD

**Issue by Mark-Simulacrum** [MiguelCastillo/Brackets-InteractiveLinter#44]
Benefits:
- Allows using other extensions' linters within InteractiveLinter

Sample code to achieve:

``` js
CodeInspection.inspectFile(DocumentManager.getCurrentDocument().file).always(function (providers) {
                var results = {};
                _.forEach(providers, function (provider) {
                    _.merge(results, provider.result);
                });
                console.clear();
                _.forEach(results.errors, function (error) {
                    console.log(error);
                });
            });
```

This code lints the current file, and prints out to console each error (merging all linter results with lodash#merge. The merging would have to be worked on  - this will probably result in two errors given that both JSLint and JSHint linters are installed and that both report the same error.

**Comment by zaggino** [comment]
I couldn't find `MiguelCastillo/Brackets-InlineLinting` in the extension registry, is it released? What does it do?

I've put together a [linter for ESLint](https://github.com/zaggino/brackets-eslint), it works but I'd like to see errors inline like interactive linter does it.

**Comment by Mark-Simulacrum** [comment]
@zaggino `Brackets-InlineLinting` has not been worked on (yet) to my knowledge. The code that allows seeing errors inline is in `Brackets-InteractiveLinter`: integrating CodeInspection was planned for `Brackets-InlineLinting`, but due to time constraints, it was never started or finished.

**Comment by MiguelCastillo** [comment]
@zaggino A bit more details on inline linting...  I want to abstract out interactive linters UI and put it on top of the codeinpector API.  The intent is to basically provide interactive linter's UI for every linter that plugs into Brackets' linting API.  I have put it aside for a bit, but I would be happy to start it if there is enough interest :)

**Comment by zaggino** [comment]
I'd be definitely interested :) I'm starting a few projects where I'll be using `ESLint` which doesn't have any good extension for Brackets so I put one together, but now I'm missing nice inline stuff that I was used to. 

Personally I don't think it should be too difficult, but you'd probably need to publish a new event somewhere around here https://github.com/adobe/brackets/blob/master/src/language/CodeInspection.js#L434 for it.
